project:
  type: website
  output-dir: docs

website:
  title: "MobilityCorp"
  navbar:
    left:
      - href: index.qmd
        text: Solution
      - about.qmd

format:
  html:
    mermaid:
      theme: neutral
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    



